name: parseq
_target_: strhub.models.parseq.system.PARSeq

# Data
# patch_size: [ 4, 8 ]  # [ height, width ]
# patch_size: [ 32, 32 ]  # [ height, width ]
patch_size: [ 8, 16 ]  # [ height, width ]

# Architecture
# embed_dim: 384
embed_dim: 768
# enc_num_heads: 6
enc_num_heads: 8
enc_mlp_ratio: 4
enc_depth: 12
dec_num_heads: 12
dec_mlp_ratio: 4
dec_depth: 1

# Training
# lr: 7e-4
lr: 3e-4  # TODO 下一次训练测试
perm_num: 6
perm_forward: true
perm_mirrored: true
dropout: 0.1

# Decoding mode (test)
decode_ar: true
refine_iters: 1
